.github/ISSUE_TEMPLATE/backend_endpoint_issue_template.md
.github/ISSUE_TEMPLATE/backend_modeldb_issue_template.md
.github/ISSUE_TEMPLATE/code_spike_issue_template.md
.github/ISSUE_TEMPLATE/deployment_issue_template.md
.github/ISSUE_TEMPLATE/frontend_issue_template.md
.github/ISSUE_TEMPLATE/test_issue_template.md
README.md
frontend/src/components/SignUp.vue

The main goal of this pull request is to fix project naming and improve user experience in the signup form.
- Corrected the `README.md` title from "BookHub" to "ReadHub".
- Fixed the error that caused the signup page, `SignUp.vue`, to reload after clicking the signup button for the first time.

Fix: Signup page reload and update project name in README

---

README.md
backend/README.md

The goal of this pull request is to bring the changes from`release/v1.0.0` to `develop`.
- Two README files have also been added for better documentation of the project setup and the functionality of the features implemented. These README files aim to guide new developers in understanding the project structure and how to contribute effectively.

R.v1.0.0: Documentation Enhancement 

---

backend/app/api/routes/users.py

**Description**
This PR introduces a new endpoint to fetch the top 5 users based on a given keyword. The search functionality considers both the username, name and surname to provide relevant results. Basic testing has been performed, and the endpoint is functioning as expected.
**Changes**
- Added an endpoint to retrieve the top 5 users based on a keyword.
- Implemented search logic to match the keyword against name, surname and username
Example of an expected execution:

endpoint get top5 users using a keyword done

---

frontend/src/App.vue
frontend/src/components/BookPage.vue
frontend/src/components/CompactTab.vue
frontend/src/components/GridTab.vue
frontend/src/components/ListTab.vue
frontend/src/components/Navbar.vue
frontend/src/components/Suggestion.vue
frontend/src/components/Suggestions.vue
frontend/src/components/Tab.vue
frontend/src/views/SignUp.vue

The main objective of this pull request is to design and implement the logic for suggestions in the frontend.
- **Created two new components in the `/components` folder**:
- `Suggestion.vue`: A component representing an individual suggestion.
- `Suggestions.vue`: A component representing a group of suggestions.
- **Modifications in `Navbar.vue`**:
- Added the `Suggestions.vue` component to `Navbar.vue`.
- Implemented a function called `filterSuggestions()` to check for errors, special characters, and cases where no match is found in the search input. This function also filters matching suggestions from static arrays within the class.
- Added a function called `hasSpecialCharacters()` that checks whether the input contains any special characters.
- **Other Changes**:
- Implemented dynamic …

 US3.1_Task7: Implement Suggestions

---

backend/Dockerfile
backend/app/main.py
frontend/config/dev.env.js

Backend Functionality in Production Confirmed
The backend is now fully functional in the production environment. All endpoints have been thoroughly tested, and their responses align with the expected behavior.
Feel free to review the code.

Backend working in production (endpoints tested)

---

backend/app/api/routes/users.py

Now the function is named correctly, and the search is limited by 5 users.
The destintation branch is corrected.

bug-fix-users-top5

---

backend/Dockerfile
backend/app/main.py
frontend/config/dev.env.js
frontend/src/components/FilterHeader.vue
frontend/src/components/Navbar.vue
frontend/src/services/BookService.js
frontend/src/services/UserService.js
frontend/src/views/HomePage.vue

**Description**
The main goal of this PR is to integrate the backend API to update the library by applying filters to display only this type of books.
**Changes**
BookService: Implemented the filterBooks method to handle fetching filtered books from the backend based on selected genres.
HomePage: Added logic in the handleGenresUpdate method to dynamically update the searchResults with the books fetched from the backend when filters are applied.
FilterHeader: Connected the @genres-updated event to handleGenresUpdate method, ensuring the library view reflects the applied filters.
**Screenshot**

Update library using filters

---

backend/app/tests/test_books.py
backend/app/tests/test_service.py

Integrated multiple testing methods (test_service.py and test_books.py) to enhance coverage and ensure functionality.

Integrate several testing methods (test_service.py + test_books.py)

---

frontend/src/components/FilterHeader.vue

The goal of this update is to enhance the design of the `FilterHeader.vue` component by introducing a visual line element.
- Added a `span` element to represent the line in `FilterHeader.vue`

US4_Task_4: Resolve line design issue in FilterHeader

---

frontend/src/views/LogIn.vue

The main goal of this pull request is to fix project link.
- Fixed the error link in the login page, `LoginPage.vue`, to got to the signup form.

Fix: Router link in the login

---

.github/workflows/test.yml
backend/app/api/routes/users.py
backend/app/tests/test_users.py
backend/poetry.lock
backend/pyproject.toml
frontend/src/components/CategoryTab.vue
frontend/src/components/CompactTab.vue
frontend/src/components/GridPlaceHolder.vue
frontend/src/components/ListTab.vue
frontend/src/components/Navbar.vue
frontend/src/components/Tab.vue
frontend/src/services/UserService.js
frontend/src/views/HomePage.vue

This PR addresses several issues across different components, improves functionality, and enhances the user experience.
- Fixed `test.yml` for automated testing, and added a GitHub Action for Python Coverage.  
- Fixed `Tab.vue` and `CompactTab.vue` to correctly import `GridPlaceHolder.vue` instead of `GridPlaceholder.vue`.  
- Fixed `backend/app/tests/test_users.py`; the `test_read_top5_matched_users` now passes successfully.  
- Fixed `backend/app/api/users.py` by correcting the `read_user_by_id` method.  
- Fixed search redirection issue when a user profile is not found.  
- Added a new user service, `readUserById`, in `UserService.js`.  
- Corrected `Navbar.vue` method `startSearch` to call the `readUserById` service.  
- Added a new loading animation to the search input field in …

Fix: Various Bug Fixes and Improvements

---

backend/app/api/routes/users.py

Implemented a PUT endpoint to update user fields dynamically.
Added support for updating the password with bcrypt encryption.
Ensured proper validation to check for user existence.
Improved error handling for database connectivity and invalid inputs.
+ Verified updates for individual and multiple fields.
+ Confirmed password update works as expected.

Added functionality to update user fields, including password

---

backend/app/api/routes/books.py

Added endpoints for comments and ratings functionality:
POST /books/:id/comments: Allows users to submit comments and ratings for a specific book. Validates that both the user and the book exist, and ensures the rating is between 1 and 5 before inserting the data into the database.
GET /CommentRatingPerBook/:idBook: Retrieves all comments and ratings for a specific book. Returns the comment text, rating, and the username of the user who submitted the comment.
Changes made:
Implemented logic for checking if a user and book exist before inserting a comment or rating.
Included user details (username) in the response when fetching comments and ratings.
Added validation for rating to ensure it's within the range of 1 to 5.

GET and POST book ratings done and manually tested their funcionalities

---

backend/app/api/routes/books.py
backend/app/api/routes/users.py
backend/app/tests/test_books.py

The main goal of this pull request is to implement validation for posting book ratings.
- Updated `conftest.py` to initialize the database for testing by calling the `init_db(cursor)` method from `app.core.db`. This method creates a user and a book specifically for test purposes to ensure consistent test data.
2. **New Tests**  
- Added five new tests in `test_books.py` to validate the creation of a rating for a book, including both valid and invalid input scenarios. (Addresses issue #96 ).
3. **Backend Refactor**  
- Refactored `app/api/routes/books.py`:
- Updated endpoints to use new dependency injection for database sessions.
- Removed redundant imports and optimized logic for better maintainability and readability.

US6_Task6: Validate POST Book Rating

---

backend/app/api/routes/books.py
backend/app/core/db.py
backend/app/tests/test_books.py

The objective of this pull request is to implement validation for deleting book ratings.
- Updated the `init_db(cursor)` method in `app.core.db` to create a user, a book, and a book rating specifically for testing, ensuring consistent and controlled test data.
2. **New Tests**  
- Added three new tests in `test_books.py` to validate the deletion of a book rating, covering both valid and invalid input scenarios (Addresses issue #98 ).
3. **Backend Refactor**  
- Refactored `app/api/routes/books.py`:
- Updated endpoints to incorporate new dependency injection for database sessions.
- Removed redundant imports and optimized code for improved maintainability and readability.

US7_Task3: Validate DELETE book rating

---

backend/app/api/routes/books.py
backend/app/tests/test_books.py

The objective of this pull request is to implement validation for receiving books.
- Added two new tests in `test_books.py` to validate the process of receiving books, covering both valid and invalid input scenarios (Addresses issue #81 ).
2. **Backend Refactor**  
- Refactored `app/api/routes/books.py`:
- Updated endpoints to incorporate new dependency injection for database sessions.
- Removed redundant imports and optimized code for improved maintainability and readability.

US5_Task2: Validate GET all books

---

backend/app/api/routes/books.py
backend/app/core/db.py
backend/app/tests/test_books.py

The objective of this pull request is to implement validation for receiving the book ratings of a book.
- Updated the `init_db(cursor)` method in `app.core.db` to create a user, two books, and a book rating specifically for testing, ensuring consistent and controlled test data.
2. **New Tests**  
- Added four new tests in `test_books.py` to validate receiving book ratings, covering both valid and invalid input scenarios (Addresses issue #97).
3. **Backend Refactor**  
- Refactored `app/api/routes/books.py`:
- Updated endpoints to incorporate new dependency injection for database sessions.
- Removed redundant imports and optimized code for improved maintainability and readability.

US6_Task7: Validate GET book rating

---

backend/app/api/routes/books.py
backend/app/tests/test_books.py
frontend/src/components/BookPage.vue
frontend/src/components/Navbar.vue
frontend/src/views/HomePage.vue

This Pull Request integrates the `userstory/US5-access-book-details` branch into `develop` after completing the tasks related to testing the retrieval of book information and the frontend implementation of the detailed book page.  
- [PR #109](#): Validation for GET all books  
- [PR #112](#): Development of the detailed book information page

Second Integration of userstory/US5-access-book-details into develop

---

backend/app/api/routes/books.py
backend/app/api/routes/users.py
backend/app/tests/test_books.py

This Pull Request integrates the `userstory/US6-leave-comments` branch into `develop` after completing the tasks related to testing and implementing the comment functionality.  
- [PR #92](#): Create book rating tables, POST, and GET book ratings.  
- [PR #101](#): Update the average rating of a book.  
- [PR #106](#): Validate POST Book Rating.  
- [PR #106](#): Validate GET Book Rating.

First Integration of userstory/US6-leave-comments into develop

---

backend/app/api/routes/books.py
backend/app/core/db.py
backend/app/tests/test_books.py

This Pull Request integrates the `userstory/US7-delete-comments-rating` branch into `develop` after completing the tasks related to testing and implementing the delete comment functionality.  
- [PR #104](#): Implement DELETE Book Rating.  
- [PR #107](#): Validate DELETE Book Rating.

First Integration of userstory/US7-delete-comments-rating into develop

---

backend/app/api/routes/users.py
backend/app/crud/user.py

The main goal is to abstract the CRUD operations from `backend/app/api/routes/users.py` to facilitate the creation of unit tests for these operations in the future.  
- Moved CRUD operations from `backend/app/api/routes/users.py` to a new file: `backend/app/crud/user.py`.  
- Renamed `backend/app/tests/test_users.py` to `backend/app/tests/integration/test_users.py` to clarify that these are integration tests.

US17_Task2: Refactor Users CRUD Operations 

---

backend/app/tests/unit/test_comment.py

The objective of this pull request is to implement and validate the CRUD operations for comments.  
- Added new tests in `backend/app/tests/unit/test_comment.py` to validate the processes of creating, reading, updating, and deleting a comment (Addresses issue #124).

US17_Task6: Test CRUD Operations for Comments

---

backend/app/tests/unit/test_book.py

The objective of this pull request is to implement and validate the CRUD operations for books.  
- Added new tests in `backend/app/tests/unit/test_book.py` to validate the processes of creating, reading, updating, and deleting a book (Addresses issue #136).

US17_Task4: Test CRUD Operations for Books

---

backend/app/tests/unit/test_user.py

The objective of this pull request is to implement and validate the CRUD operations for users.  
- Added new tests in `backend/app/tests/unit/test_user.py` to validate the processes of creating, reading, updating, and deleting a user (Addresses issue #138).

US17_Task 5: Tested CRUD for users.

---

backend/app/api/routes/login.py
frontend/src/components/BookPage.vue
frontend/src/components/FilterHeader.vue
frontend/src/components/Navbar.vue
frontend/src/store/store.js
frontend/src/views/HomePage.vue
frontend/src/views/LogIn.vue
frontend/src/views/SignUp.vue

**Description**
This PR introduces an authentication system to identify the logged-in user.
**Changes**
- Modified the login process to return an access token that encodes the user ID.
- Replaced the storage of the username in the browser's localStorage with the access token.

Token-Based Authentication System

---

frontend/src/components/Navbar.vue
frontend/src/store/store.js

**Description**
This PR adds a logout functionality to the Navbar component.
**Changes**
- A tooltip with a logout icon is added in the Navbar Component: , which triggers the logOut method on click.
- A logOut Method which clears the user data in the Vuex store and redirects to the homepage.
- The clearUser action is added in store to clear the username from the state and localStorage.

US16-Task1-Log-out-button

---

frontend/src/components/BookPage.vue
frontend/src/components/DefaultLibrary.vue
frontend/src/services/BookService.js
frontend/src/views/HomePage.vue

Implement a feature that allows users to add books to their library using a button.
-  **frontend/src/components/BookPage.vue:**  
- Added the "Add Book" button that allows users to add books to their collection.
- Integrated logic to handle the button click, sending the book data to the backend service for saving.
-  **frontend/src/components/DefaultLibrary.vue:**  
- Updated the library view to include the new "Add Book" functionality.
- Adjusted rendering logic to accommodate changes in the list of books when a new book is added.
- **frontend/src/services/BookService.js:**  
- Added a new service method for handling the request to add a book to the user’s library.
- Integrated API calls for saving a book to the backend.
- **frontend/src/views/HomePage.vue:**  
- Integrated the new …

US8_Task2: Develop button for add book

---

frontend/src/components/BookPage.vue
frontend/src/components/DefaultLibrary.vue

This Pull Request introduces the functionality to delete a book from the user's "My Books" list. It includes the addition of a button for removing books from the library and updates to the relevant components and services.
- **frontend/src/components/BookPage.vue**: Added a button for deleting books from the user's library and integrated the delete functionality.

US9_TasK1: Develop button to delete book from MyBooks

---

frontend/src/components/BookPage.vue
frontend/src/components/DefaultLibrary.vue

This Pull Request merges the `userstory/US9-edit-my-books` branch into `develop`. It encompasses the completion of tasks related to edit elements from the "My Books" feature.
- [PR #191](#): Add button and logic for delete a book to the user’s library.

Second Integration of userstory/US9-edit-my-books into develop

---

backend/app/api/routes/books.py
backend/app/crud/rating.py

Added get_books_ratings_by_user() in routes/books.py and get_books_with_ratings_by_user in crud/rating.py to get books ratings by user.

Created endpoint and crud to Get Books Ratings By User.

---

.github/workflows/test_frontend.yml
frontend/package-lock.json
frontend/package.json
frontend/src/components/BookPage.vue
frontend/src/components/CompactTab.vue
frontend/src/components/FilterHeader.vue
frontend/src/components/GridLibrary.vue
frontend/src/components/GridTab.vue
frontend/src/components/ListTab.vue
frontend/src/components/Navbar.vue
frontend/src/components/Profile.vue
frontend/src/components/Suggestion.vue
frontend/tests/test_validate_book.ts
frontend/tests/test_validate_delete_rating.ts
frontend/tests/test_validate_user_page.ts
frontend/utils/encoding.js

Implement functionality to encode and decode URLs across various components in the frontend to ensure safe and correct query parameters for navigation.
- **Workflow**: `.github/workflows/test_frontend.yml`: Modified Selenium tests to add the new `.env` variable.
- **Package Updates for Encryption and Decryption**:`frontend/package-lock.json` and `frontend/package.json`.
- **Component Refactors to Handle Encoded URLs**:
- `frontend/src/components/BookPage.vue`
- `frontend/src/components/CompactTab.vue`
- `frontend/src/components/GridLibrary.vue`
- `frontend/src/components/GridTab.vue`
- `frontend/src/components/ListTab.vue`
- `frontend/src/components/Navbar.vue`
- `frontend/src/components/Profile.vue`
- `frontend/src/components/Suggestion.vue`
- **Test Refactors**: Updated test cases to …

US18_TasK1: Implement url encoding and decoding

---

.github/workflows/test_frontend.yml
frontend/package-lock.json
frontend/package.json
frontend/src/components/BookPage.vue
frontend/src/components/CompactTab.vue
frontend/src/components/FilterHeader.vue
frontend/src/components/GridLibrary.vue
frontend/src/components/GridTab.vue
frontend/src/components/ListTab.vue
frontend/src/components/Navbar.vue
frontend/src/components/Profile.vue
frontend/src/components/Suggestion.vue
frontend/tests/test_validate_book.ts
frontend/tests/test_validate_delete_rating.ts
frontend/tests/test_validate_user_page.ts
frontend/utils/encoding.js

This Pull Request merges the `userstory/US18-implement-url-encoding-and-decoding` branch into `develop`. It encompasses the completion of tasks related to URL encoding and decoding.
- [PR #201](#): Implement URL encoding and decoding.

First Integration of userstory/US18-implement-url-encoding-and-decoding into develop

---

frontend/src/components/Tab.vue

The main goal of this pull request is to fix the "Show All" link on the main page.  
- Fixed the `Tab.vue` component to ensure it functions correctly.

Fix: Show all books link
